import fs from "fs";
import path from "path";

const publicDir = path.join(process.cwd(), "public");
const contentDir = path.join(process.cwd(), "content");

// Read the base profile (already generated by generate-llms-txt.ts)
const llmsFullPath = path.join(publicDir, "llms-full.txt");
if (!fs.existsSync(llmsFullPath)) {
  console.error("public/llms-full.txt not found — run generate-llms-txt.ts first");
  process.exit(1);
}
const llmsFull = fs.readFileSync(llmsFullPath, "utf-8");

// Read career stories if they exist
const careerStoriesPath = path.join(contentDir, "chat-context-career-stories.md");
let careerStories = "";
if (fs.existsSync(careerStoriesPath)) {
  const raw = fs.readFileSync(careerStoriesPath, "utf-8");
  // Strip the frontmatter/header (everything before the first ## section)
  const firstSection = raw.indexOf("\n## ");
  if (firstSection !== -1) {
    careerStories = raw.slice(firstSection).trim();
  }
}

// Combine
const chatContext = [
  llmsFull,
  "",
  "---",
  "",
  "## Career Stories — Detailed Context",
  "",
  careerStories || "(Career stories not yet written — base profile only)",
].join("\n");

fs.writeFileSync(path.join(publicDir, "chat-context.txt"), chatContext);
console.log("Generated public/chat-context.txt");
